apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: capstone
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: ashidubey/capstone:73c6db4bc9846dd0eef12da6558484cba2fab4aa
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_HOST
            value: "mongodb-0.mongodb"
          - name: MONGODB_PORT
            value: "27017"


